### ISSUE TITLE
top letter is chooped when droptext is used inside slivers

### ISSUE THREAD

**Issue by fremfi** [mtiziano/drop_cap_text#1]
Not sure the reason why, every where else on my app the droptext widget renders fine, but its chopped inside slivers. here is sample code;

`class Playground extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.all(50.0),
              child: DropCapText(
                'Random',
                style: TextStyle(fontSize: 24),
                dropCapStyle: TextStyle(fontSize: 60),
                dropCapPadding: EdgeInsets.only(top: 5.0, right: 5.0),
              ),
            ),
          )
        ],
      ),
    );
  }
}`

**Comment by mtiziano** [comment]
Fixed with version 1.0.2
