### ISSUE TITLE
How to add space between the text data and the DropCap child.

### ISSUE THREAD

**Issue by MstrZeroOne** [mtiziano/drop_cap_text#14]
I'm using drop_cap_text everything is OK but when text is not multiline it shows text in right but I want to show it on the left.

![Capturebbbb](https://user-images.githubusercontent.com/70561437/103421681-43006900-4bbb-11eb-9d32-7a40d47356bc.PNG)

![Capturebbbb](https://user-images.githubusercontent.com/70561437/103421775-c28e3800-4bbb-11eb-99e0-5643343475f0.PNG)

**Comment by MstrZeroOne** [comment]
کشادا چرا جواب نمیدین

**Comment by MstrZeroOne** [comment]
Why you are not answering Koshada?

**Comment by mtiziano** [comment]
@MstrZeroOne example code? thanks

**Comment by mtiziano** [comment]
for adding space you can use **dropCapPadding**
example: `dropCapPadding: EdgeInsets.only(bottom: 24, right: 24)`
