### ISSUE TITLE
Dark and Light theme issue

### ISSUE THREAD

**Issue by Effendi-lab** [mtiziano/drop_cap_text#17]
All text except the dropcap characters are has orange highlight colour.
![1617121453498](https://user-images.githubusercontent.com/63195268/113023086-328d6980-917d-11eb-9b6c-09259706838e.jpg)

**Comment by Effendi-lab** [comment]
Row(
            children: [
              Expanded(
                child: Card(
                  elevation: 5.0,
                  child: DropCapText("Effendi is here so try and come please, try and find the way to the village"
                      "Effendi is here so try and come please, try and find the way to the village",
                  dropCapChars: 1, dropCapPosition: DropCapPosition.start,
                    mode: DropCapMode.inside, parseInlineMarkdown: true,
                    forceNoDescent: true, dropCap: null,
                    style: TextStyle(fontSize: 30.0),
                   
                  ),
                ),
              ),
            ],
          )

**Comment by mtiziano** [comment]
yes sorry, fixed with 1.1.2
