### ISSUE TITLE
Cant seem to reduce the bottom space/padding on the dropcap using the api. I'd like to remove the spacing below the L

### ISSUE THREAD

**Issue by fremfi** [mtiziano/drop_cap_text#2]
<img width="299" alt="Screen Shot 2019-12-04 at 1 43 28 AM" src="https://user-images.githubusercontent.com/20648834/70119164-b261fd00-1637-11ea-8678-dea9ab2c3505.png">

**Comment by fremfi** [comment]
would also like to avoid the line break happening after "when an ..."

**Comment by mileusna** [comment]
Same here, I use it with images and I always get this awkward spacing below image where at least one more line of text should fit.
<img width="472" alt="Screen Shot 2019-12-11 at 16 07 18" src="https://user-images.githubusercontent.com/4697935/70633193-6ebb5480-1c30-11ea-8c44-34d0a378dced.png">

**Comment by mileusna** [comment]
I have managed to fix this issue in code. I have created pull request so the @mtiziano can merge it to the main project after review.

**Comment by mtiziano** [comment]
Fixed with version 1.0.2.
Use `forceNoDescent: true` to remove descent space reserved for characters like **Ç** or **lowercase g**
