### ISSUE TITLE
Allow us to pass RichText instead of a String

### ISSUE THREAD

**Issue by SaeedZeroOne** [mtiziano/drop_cap_text#21]
Hey there!
This package of yours is the closest thing I've found to putting an image inline with the text, however, it would be awesome if we could use RichText instead of a simple string. 

I believe it is possible to do so as the TextSpan you're using inside the code accepts TextSpans as its children, but I'm not sure.

**Comment by ari-borlaza** [comment]
yes, please! this could solve my issues, for my texts!

**Comment by thareshjose** [comment]
@SaeedZeroOne What was the resolution provided for this? Was this closed, as the developer/maintainers of this package hasn't responded back in over 2 years?
