### ISSUE TITLE
different fonts for drop cap and the copy text

### ISSUE THREAD

**Issue by inteist** [mtiziano/drop_cap_text#7]
Allow to specify font for the drop cap separate from the main text
Stylistic and calligraphic fonts are often used for the dropcap but not for the main text.

**Comment by mtiziano** [comment]
> Allow to specify font for the drop cap separate from the main text
> Stylistic and calligraphic fonts are often used for the dropcap but not for the main text.

@inteist  You can already do this with **dropCapStyle** attribute

        

    DropCapText(
        myText,
        dropCapStyle: TextStyle(
            fontFamily: 'Monospace'
       ))
