### ISSUE TITLE
Different textstyles next to an image

### ISSUE THREAD

**Issue by tomoerlemans010** [mtiziano/drop_cap_text#8]
First of, thanks for the great plugin! 

The plugin almost accomplishes what I try to do. Except for one thing. I'd like to have an inline image, with text next to it. But this text consists out of a header and out of a body. And the header should have a different font-size. E.g.:

![image](https://user-images.githubusercontent.com/61277160/77105247-9c791c00-6a1d-11ea-99fa-48e7b2b4b38a.png)

Any suggestions on how I might accomplish this?

**Comment by mtiziano** [comment]
you can start by using the property "parseInlineMarkdown" as true, so you could provide a markdown like text as the example below

`text = "**A floating Image**\nIste quidem veteres...."`

it will make the first line **Bold** but it will not make it bigger in font-size.
I'm going to support full markdown in the future

**Comment by ihepta** [comment]
@mtiziano you can consider about passing a "RichText|Text|TextSpan..." widget to your plugin rather than only a text String.

**Comment by mtiziano** [comment]
maybe in the future
