### ISSUE TITLE
DropCapText does not change color when using dark theme 

### ISSUE THREAD

**Issue by Effendi-lab** [mtiziano/drop_cap_text#9]
All text in the drop cap widget does not change in color when dark theme is used instead it decrease the light brightness and cover it with some dark shade. The text remains black with white background. Could you add a property to DropCapText widget to make it selectable. Thanks. 
Below is an image. 
![Screenshot_20200408_230527](https://user-images.githubusercontent.com/63195268/78841887-1897cb80-79ee-11ea-8ebd-b3df55201b76.jpg)

**Comment by mtiziano** [comment]
Nice feedback, i'm going to support it in next release

**Comment by mtiziano** [comment]
supported in 1.1.0
